votingapp:
  build: ./voting-app/.
  ports:
    - "5000:80"
  links:
    - "redis"

redis:
  image: hypriot/rpi-redis
  ports: ["6379"]

worker:
  build: ./worker
  links:
    - "redis"
    - "db"

db:
  image: zsoltm/postgresql-armhf
  volumes:
    - "myvolume:/var/lib/postgresql/data"

resultapp:
  build: ./result-app/.
  ports:
    - "5001:80"
  links:
    - "db"

